services:
  app:
    container_name: amocrm-merge-duplicates
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always
    environment:
      - PORT=3000
